logcheck: add type alias support
With recent dependencies (= `go get -u ./...`), type aliases are reported as
`types.Alias` instead of `types.Named`. Found initially in Kubernetes,
confirmed with unit tests:

    --- FAIL: TestAnalyzer (3.05s)
        --- FAIL: TestAnalyzer/Function_call_parameters (0.20s)
            analysistest.go:713: parameters/parameters.go:54: no diagnostic was reported matching `Additional arguments to Info should always be Key Value pairs. Please check if there is any key or value missing.`
            analysistest.go:713: parameters/parameters.go:55: no diagnostic was reported matching `Additional arguments to Error should always be Key Value pairs. Please check if there is any key or value missing.`
            analysistest.go:713: parameters/parameters.go:65: no diagnostic was reported matching `Key positional arguments are expected to be inlined constant strings. Please replace 1 provided with string value`
            analysistest.go:713: parameters/parameters.go:67: no diagnostic was reported matching `Key positional arguments are expected to be inlined constant strings. Please replace 1 provided with string value`
            analysistest.go:713: parameters/parameters.go:80: no diagnostic was reported matching `Additional arguments to Info should always be Key Value pairs. Please check if there is any key or value missing.`
        --- FAIL: TestAnalyzer/helpers (0.16s)
            analysistest.go:713: helpers/doNotAllowDirectCalls.go:34: no diagnostic was reported matching `function "WithName" should be called through klogr.LoggerWithName`
            analysistest.go:713: helpers/doNotAllowDirectCalls.go:35: no diagnostic was reported matching `function "WithValues" should be called through klogr.LoggerWithValues`
        --- FAIL: TestAnalyzer/Detect_incomplete_fmt.Stringer (0.21s)
            analysistest.go:713: stringer/stringer.go:27: no diagnostic was reported matching `The type \*stringer.config inherits \(\*k8s.io/apimachinery/pkg/apis/meta/v1.TypeMeta\).String as implementation of fmt.Stringer, which covers only a subset of the value. Implement String\(\) for the type or wrap it with TODO.`
    FAIL
    FAIL	sigs.k8s.io/logtools/logcheck	3.059s

We need to resolve type aliases. We can't just call Underlying, that
resolves to an unnamed type. We need to use Rhs instead, which depends
on Go 1.23.